### ISSUE TITLE
Solve Problems with GWT

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-lib#131]
we currently have Compile Errors in GWT tests (build works fine)
- ignore erros
- remove GWT support
- find different GWT Gradle plugin that works with Gradle 5
- install http://storage.googleapis.com/gwt-eclipse-plugin/v3/release/ with oomph (not sure if this will help)
- use something else than gradle to build

**Comment by cdietrich** [comment]
in 2.16 deprecate, in 2.17 remove.

**Comment by cdietrich** [comment]
Moved removal to 2.18

**Comment by cdietrich** [comment]
cc @ArneDeutsch @szarnekow

**Comment by mbudnick** [comment]
I would change to https://github.com/esoco/gwt-gradle-plugin (license LGPL-3.0). It seems to be maintained and I manged to fix the compile errors.
An alternative could be https://github.com/ascendtech/gwt-gradle (license Apache-2.0). But this project is not even one year old.
An secound alternative could be https://github.com/big-guy/gwt-gradle-plugin (no license). There are few commits for mantaining new gradle versions, but no up to date releases for this.

@cdietrich How can I check now if the test is executed and pass?

**Comment by cdietrich** [comment]
you can run the bash script.
or you create a branch and open a WIP pull request.
also make sure there are no gradle 6.0 deprecation warnings

**Comment by cdietrich** [comment]
thx for the fix @mbudnick
