### ISSUE TITLE
xtend-lib 2.17.0.M1 breaks Maven resolution for lsp4j

### ISSUE THREAD

**Issue by Blaisorblade** [eclipse/xtext-lib#146]
It appears your new milestone release depends on a missing artifact, and since LSP4J depends on a version range, existing LSP4J releases appear non-functional.

EDIT: Beware I'm no Maven expert.

1. org.eclipse.xtend.lib 2.17.0.M1 depends on missing artifact `xtext-dev-bom` (per https://search.maven.org/artifact/org.eclipse.xtend/org.eclipse.xtend.lib/2.17.0.M1/jar)

2. org.eclipse.lsp4j.generator 0.5.0 depends on org.eclipse.xtend.lib `[2.11.0,3)`, so picks up the new version:
https://search.maven.org/artifact/org.eclipse.lsp4j/org.eclipse.lsp4j.generator/0.5.0/jar

3. build failures follow. From our CI: http://dotty-ci.epfl.ch/lampepfl/dotty/9751/5

**Comment by Blaisorblade** [comment]
The missing artifact appears [published](https://search.maven.org/artifact/org.eclipse.xtext/xtext-dev-bom/2.17.0.M1/pom). Closing.

**Comment by kthoms** [comment]
Be patient, young padawan, Maven Central synching slowly is and sleeping in the night a good choice is ;-)
