### ISSUE TITLE
Move tests

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-lib#3]
We should move the lib tests to this repository. 
Many of them are here https://github.com/eclipse/xtext-extras/tree/master/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/lib and https://github.com/eclipse/xtext-xtend/tree/master/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/lib

**Comment by spoenemann** [comment]
We could consider moving the tests into a new source folder of xbase.lib.

**Comment by svenefftinge** [comment]
I decided for a separate project because we need one for xtend.lib, too (for active annotations tests).
