### ISSUE TITLE
DefaultLineDelimiter super src missing from published GWT artifacts in 2.11.0

### ISSUE THREAD

**Issue by djozis** [eclipse/xtext-lib#40]
Checking here: http://central.maven.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib.gwt/2.11.0/
And here: http://central.maven.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.11.0/
I was not able to find any jars (sources or normal) containing this file: https://github.com/eclipse/xtext-lib/blob/master/org.eclipse.xtext.xbase.lib.gwt/src-super/org/eclipse/xtend2/lib/super/org/eclipse/xtend2/lib/DefaultLineDelimiter.java

As a result, I could not get DefaultLineDelimiter.get to work client-side in GWT using Xtend/Xbase 2.11.0 (so  it seems to me that '''strings''' are broken on client side).

In 2.10.0, org.eclipse.xtext.xbase.lib.gwt-2.10.0.jar contained this file under: org/eclipse/xtend2/lib/super/org/eclipse/xtend2/lib/DefaultLineDelimiter.java

This seems to be broader in that all super srcs seem to be absent.

**Comment by svenefftinge** [comment]
A restructuring issue, I suppose

**Comment by cdietrich** [comment]
I assume we can do thw follwing.

adapt *.lib/build.gradle and add a tasks like this

```
task copyGwtSources(dependsOn: 'build') {
	doLast {
	
		ant.copy(toDir: '../org.eclipse.xtext.xbase.lib.gwt/build/gwtSources', verbose: true) {
			sourceSets.main.java.addToAntBuilder(ant, 'fileset', FileCollection.AntType.FileSet)
		}
		ant.delete {	
			fileset(dir:'../org.eclipse.xtext.xbase.lib.gwt/build/gwtSources') {
				or {
					not {
					contains(text: '@GwtCompatible')
					}
					contains(text: 'emulated = true')
				}
			}
		}
	}

}
```

adapt *.lib.gwt/build.gradle and customize it like this

``` 
jar {
	dependsOn ':org.eclipse.xtext.xbase.lib:copyGwtSources'
	from('.') {
		include 'OSGI-INF/**'
	}
	from('build/gwtSources') {
		include '**/*.java'
	}
}
``` 

we might have to adapt the libgwt.xmls in a way that sources are searched in /

unfortunately i know too few on gwt.

@svenefftinge @spoenemann can you help?

**Comment by cdietrich** [comment]
@djozis would you be so kind and test the 2.12.0 snapshot from here http://services.typefox.io/open-source/jenkins///job/xtext-lib/job/cd_issue40/lastSuccessfulBuild/artifact/build/maven-repository/

**Comment by djozis** [comment]
@cdietrich I had to add some of the other builds too for transitive dependencies:
```
    maven { url 'http://services.typefox.io/open-source/jenkins/job/xtext-lib/job/cd_issue40/lastSuccessfulBuild/artifact/build/maven-repository/' }
    maven { url 'http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/master/lastSuccessfulBuild/artifact/build/maven-repository/' }
    maven { url 'http://services.typefox.io/open-source/jenkins/job/xtext-core/job/master/lastSuccessfulBuild/artifact/build/maven-repository/' }
    maven { url 'http://services.typefox.io/open-source/jenkins/job/xtext-extras/job/master/lastSuccessfulBuild/artifact/build/maven-repository/' }
```
Yes, the issue was solved. I could show that switching between the 2.12.0-SNAPSHOT versions and the 2.11.0 versions would cause the same code to succeed and fail respectively.

**Comment by cdietrich** [comment]
maybe a condidate for 2.11.1 as well

**Comment by djozis** [comment]
I'm having a lot of trouble doing any string concatenation on client side of GWT due to this error. Is there any work-around or timeline on when 2.11.1 may be released?

I tried doing concatenation in a Java method using StringBuilder and it still failed due to the DefaultLineDelimiter compile issue. Removing that attempt to concatenate and using an empty string instead then compiled fine.

**Comment by cdietrich** [comment]
@svenefftinge @spoenemann can you please comment on the timeline of the 2.11.1 release?

@djozis is it possible you use the 2.12.0-SNAPSHOTS for xbase.lib/xbase.lib.gwt/xtend.lib/xtend.lib.gwt only

**Comment by djozis** [comment]
Thanks for the suggestion @cdietrich - yesterday I figured out why I got that error with even normal concatenation. One of the strings I was trying to concatenate was coming from a method with a templated string body - it was otherwise not being called from the client side in GWT. Referencing it seemed to cause GWT to try to compile it for the client side and fail. I should be able to work around this issue now until there's a release which solves it.

**Comment by spoenemann** [comment]
In general, we don't have fixed plans for service releases. We don them as soon as we have enough content. Since preparing a release is quite a lot of work in the case of Xtext, it would be nice to gather other important issues in addition to this one &ndash; if it's fine for you to work with the snapshots for some time.

**Comment by mxro** [comment]
I don't know if this is related to this issue but I have come across the following problem:

Using `2.11.0` from Maven Central, I was not able to get anything to compile with GWT. In particular, I got the error that GWT could not find the source for `org.eclipse.xtext.xbase.lib.Lib` (this is referenced in the Xtend GWT library).

Thank you!

**Comment by cdietrich** [comment]
Yes this is the same issue

**Comment by djozis** [comment]
@mxro All the .java sources seem to be absent from the gwt versions of the jars - to work around this, I've been adding the sources jar to my dependencies - it's not perfect but it's good enough for me for now. Gradle example of what has worked for me: https://github.com/djozis/gradle-gwt-xtend-autogwt-example/blob/master/build.gradle#L66-L71
Biggest loss with this approach imo is `'''template strings'''` don't work on client side in GWT.

**Comment by mxro** [comment]
@djozis Thank you, that's looks like a good approach. Unfortunately, I am using Maven and don't think I can find a good solution to download the sources for the project *and the projects dependent on it* ...

**Comment by svenefftinge** [comment]
@mxro could you use the snapshot version for now?

**Comment by mxro** [comment]
I downgraded to 2.10.0 for now, which works fine. I'll be happy to wait until the next release. Thank you!
