### ISSUE TITLE
Decide on complete move to Java 8

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-lib#51]
to complete #30 we need to decide if we want to move to java 8

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=486390 as well

**Comment by svenefftinge** [comment]
Is this hurting anybody atm? The ticket you referenced is a bit old.

**Comment by cdietrich** [comment]
a year old is not so old for an xtext bug ;)

**Comment by svenefftinge** [comment]
I am not aware of any users that are still on Java 6.

**Comment by cdietrich** [comment]
well we have issues like this one https://github.com/eclipse/xtext-lib/issues/45

**Comment by ewillink** [comment]
The platform has pretty much moved to Java 8:

https://www.eclipse.org/projects/project-plan.php?projectid=eclipse

so Java 6 should only be appropriate as a runtime compatability for users. But is it helpful to give them the illusion that Java 6 works when they will hit an obscure gotcha as soon as they do anything interesting?

**Comment by cdietrich** [comment]
yes the only ones could be android users.
i dont know how good the android java 7 backcompiler works with our code

**Comment by svenefftinge** [comment]
People use Xtend and Xbase DSLs on GWT and android. Which AFAIK do not support Java 8?

Since our latest version is pretty stable we could decide to just no longer support them in coming versions. That said, I‘m not sure the benefits are worth it.

**Comment by cdietrich** [comment]
my knowledge is they both do support partially. thus the question if we use features they dont and how to test. @szarnekow  and me even like to go to guava 23 in supported ranges.
but we are still need to tie our maven/gradle dependencies against the old version since there is no such thing like a target platform in gradle

**Comment by ewillink** [comment]
If Guava 23 is in use (by someone) for Photon, please ensure that it is in Orbit soon so that we do not have another last minute anguish about whether version dependencies are correctly represented in the manifests.

**Comment by szarnekow** [comment]
Since Guava's release cylces are much shorter nowadays (we are at 23.4 right now), it will be fun to see how the Eclipse processes can cope with that. But yes, having the up-to-date versions available in orbit is the right thing to do.

**Comment by ewillink** [comment]
The Guava problem will go away once:
a) an expect demonstrates that OSGI "uses" dependencies work, possibly after a P2/Equinox bug fix
b) PDE/Tycho/... tooling generates the "uses" dependencies
c) SimRel validation enforces the use of "uses" dependencies

**Comment by szarnekow** [comment]
So not very soon, I'm afraid.

**Comment by szarnekow** [comment]
> People use Xtend and Xbase DSLs on GWT and android. Which AFAIK do not support Java 8?

Looks like GWT 2.8.0 uses source level Java 8 so that would not be a blocker anymore.
We would need to check if we can define a dependency to Guava 23 in a way that allows to consume 23-android or 23-jre depending on the runtime env. 23-jre would be consumed from the Eclipse orbit. Other clients may use the other versions. Would that be an option?

**Comment by cdietrich** [comment]
id like to come back on this issue. either we need a proper way to built against java 6 or we should go to java 8

**Comment by cdietrich** [comment]
if i dont get any objections within a week i consider this a approval

**Comment by spoenemann** [comment]
No objection.

**Comment by cdietrich** [comment]
done @kthoms

**Comment by kthoms** [comment]
I consider this as done.

**Comment by cdietrich** [comment]
Updated to Java 8 with 2.14
